# Generated by Django 4.1.2 on 2022-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_close_delivery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='indicaciones',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
