databases:
  - name: virtualmenudb
    databaseName: virtualmenu
    user: virtualmenu_user

services:
  - type: web
    name: icard
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn icard.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: virtualmenu
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4